FROM ubuntu:16.04

# Set the working directory to /app
WORKDIR /app

# dnsutils: dig, nslookup, host
# net-tools: route, ip

# udev needed by lm-sensors
RUN apt-get update -y && apt-get install -y \
    curl \
    dnsutils \
    glances \
    iputils-ping \
    netcat \
    net-tools
#    hddtemp \
#    lm-sensors \
#    module-init-tools \
#    udev

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY entrypoint.sh /app/entrypoint.sh
RUN chmod 755 /app/entrypoint.sh

#ENTRYPOINT ["/app/entrypoint.sh"]

# Keep this running so to connect and test to netcat to host.
ENTRYPOINT ["ping"]
CMD ["localhost"]
